#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "=============================================="
echo " AI Web Security Scanner — Full Environment Setup"
echo "=============================================="
bash "$SCRIPT_DIR/00_setup_ubuntu.sh"
bash "$SCRIPT_DIR/01_setup_python_env.sh"
bash "$SCRIPT_DIR/02_setup_database.sh"
bash "$SCRIPT_DIR/03_install_scan_tools.sh"
echo ""
echo "Creating database tables from models..."
source "$SCRIPT_DIR/../backend/venv/bin/activate"
python3 "$SCRIPT_DIR/04_create_tables.py"
echo ""
echo "=============================================="
echo " Setup complete! Copy backend/.env.example to backend/.env, fill it in,"
echo " then start the API with: scripts/run_dev.sh"
echo "=============================================="
